
[captchasvc]
  rpcaddr = ":50051"

[httpserver]
  listenaddr = ":80"
  smode = "release"

[logsvc]
  loglevel = 4

[mysql]
  dbhost = "127.0.0.1:3306"
  dbname = "pub_platform_mgr"
  dbpassword = "1234"
  dbuser = "root"
  maxidleconn = 50
  maxopenconn = 500

[redis]
  clusteraddr = "127.0.0.1:6379"

[smssvc]
  rpcaddr = ""

[verifysvc]
  addr = ""

[wxsvc]
  accesstokenurl = "https://api.weixin.qq.com/cgi-bin/token"
  appid = ""
  appsecret = ""
  baseurl = "https://api.weixin.qq.com"
  listtmplurl = "https://api.weixin.qq.com/cgi-bin/template/get_all_private_template"
  msgtmplsendurl = "https://api.weixin.qq.com/cgi-bin/message/template/send"
