[mysql]
    dbHost = "127.0.0.1:3306"
    dbUser = "root"
    dbPassword = "1234"
    dbName = "pub_platform_mgr"
    maxIdleConn = 50
    maxOpenConn = 500

[httpServer]
    listenAddr = ":80"
    sMode = "release"

[captchaSvc]
    rpcAddr = ":50051"

[smsSvc]
    rpcAddr = ""

[logSvc]
    logLevel = 4

[wxSvc]
    appId = ""
    appSecret = ""

[redis]
    clusterAddr = "127.0.0.1:6379"

[verifySvc]
    addr = ""