
[captcha_svc]
  rpc_addr = "10.75.6.22:30463"

[http_server]
  http_server = ":80"
  server_mode = "release"

[log_svc]
  log_level = 4

[mysql]
  db_host = "10.75.2.27.nip.io:3306"
  db_name = "pub_platform_mgr"
  db_password = "Nova@9809"
  db_user = "novadev2"
  max_db_idle_conn = 50
  max_db_open_conn = 500

[redis]
  cluster_addr = "10.75.2.64.nip.io:6379,10.75.2.81.nip.io:6379,10.75.2.121.nip.io:6379,10.75.2.107.nip.io:6379,10.75.2.110.nip.io:6379,10.75.2.63.nip.io:6379,10.75.2.80.nip.io:6379,10.75.2.93.nip.io:6379"

[sms_svc]
  rpc_addr = "10.75.8.3:32571"

[verify_svc]
  addr = "www.baidu.com"

[wx_svc]
  access_token_url = "https://api.weixin.qq.com/cgi-bin/token"
  app_id = "wx1738373100645b72"
  app_secret = "715393c00c9e96c9053cfa0fd55251cc"
  base_url = "https://api.weixin.qq.com"
  list_tmpl_url = "https://api.weixin.qq.com/cgi-bin/template/get_all_private_template"
  msg_tmpl_send_url = "https://api.weixin.qq.com/cgi-bin/message/template/send"
